server:
  port: 8085

spring:
  application:
    name: Product
  data:
    mongodb:
      uri: mongodb+srv://janisarakhtaransari007:janisar007@cluster0.gg7fq.mongodb.net/test?retryWrites=true&w=majority